-- create tables

create table GS_DOC_ATTACHMENTS (
    id                   number generated by default on null as identity
                         constraint gs_doc_attachments_id_pk primary key,
    DOCNO                number,
    DOCTYP               varchar2(50 char),
    REFNO                number,
    REFTYP               varchar2(50 char),
    REFDT                date,
    REF_PAGE_NO          number,
    REFERENCE            varchar2(100 char),
    REF1                 varchar2(100 char),
    REF2                 varchar2(100 char),
    REF3                 varchar2(100 char),
    REF4                 varchar2(100 char),
    REF5                 varchar2(100 char),
    REF6                 varchar2(100 char),
    REF7                 varchar2(100 char),
    REF8                 varchar2(100 char),
    REF9                 varchar2(100 char),
    REF10                varchar2(100 char),
    ATTACHMENT           blob,
    FILE_NAME            varchar2(500 char),
    FILE_MIMETYP         varchar2(500 char),
    FILE_CHARSET         varchar2(500 char),
    STATUS               varchar2(50 char),
    ATTRIBUTE1           varchar2(100 char),
    ATTRIBUTE2           varchar2(100 char),
    ATTRIBUTE3           varchar2(100 char),
    ATTRIBUTE4           varchar2(100 char),
    ATTRIBUTE5           varchar2(100 char),
    ATTRIBUTE6           varchar2(100 char),
    ATTRIBUTE7           varchar2(100 char),
    ATTRIBUTE8           varchar2(100 char),
    ATTRIBUTE9           varchar2(100 char),
    ATTRIBUTE10          varchar2(100 char),
    CREATION_DATE        date not null,
    CREATED_BY           varchar2(255 char) not null,
    LAST_UPDATED_DATE    date not null,
    LAST_UPDATED_BY      varchar2(255 char) not null
);



-- triggers
create or replace trigger gs_doc_attachments_biu
    before insert or update
    on gs_doc_attachments
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end gs_doc_attachments_biu;
/


-- APIs
create or replace package gs_doc_attachments_api
is

    procedure get_row (
        p_id        in  number,
        p_docno   out  number,
        p_doctyp   out  varchar2,
        p_refno   out  number,
        p_reftyp   out  varchar2,
        p_refdt   out  date,
        p_ref_page_no   out  number,
        p_reference   out  varchar2,
        p_ref1   out  varchar2,
        p_ref2   out  varchar2,
        p_ref3   out  varchar2,
        p_ref4   out  varchar2,
        p_ref5   out  varchar2,
        p_ref6   out  varchar2,
        p_ref7   out  varchar2,
        p_ref8   out  varchar2,
        p_ref9   out  varchar2,
        p_ref10   out  varchar2,
        p_attachment   out  blob,
        p_file_name   out  varchar2,
        p_file_mimetyp   out  varchar2,
        p_file_charset   out  varchar2,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_docno    in  number default null,
        p_doctyp    in  varchar2 default null,
        p_refno    in  number default null,
        p_reftyp    in  varchar2 default null,
        p_refdt    in  date default null,
        p_ref_page_no    in  number default null,
        p_reference    in  varchar2 default null,
        p_ref1    in  varchar2 default null,
        p_ref2    in  varchar2 default null,
        p_ref3    in  varchar2 default null,
        p_ref4    in  varchar2 default null,
        p_ref5    in  varchar2 default null,
        p_ref6    in  varchar2 default null,
        p_ref7    in  varchar2 default null,
        p_ref8    in  varchar2 default null,
        p_ref9    in  varchar2 default null,
        p_ref10    in  varchar2 default null,
        p_attachment    in  blob default null,
        p_file_name    in  varchar2 default null,
        p_file_mimetyp    in  varchar2 default null,
        p_file_charset    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_docno    in  number default null,
        p_doctyp    in  varchar2 default null,
        p_refno    in  number default null,
        p_reftyp    in  varchar2 default null,
        p_refdt    in  date default null,
        p_ref_page_no    in  number default null,
        p_reference    in  varchar2 default null,
        p_ref1    in  varchar2 default null,
        p_ref2    in  varchar2 default null,
        p_ref3    in  varchar2 default null,
        p_ref4    in  varchar2 default null,
        p_ref5    in  varchar2 default null,
        p_ref6    in  varchar2 default null,
        p_ref7    in  varchar2 default null,
        p_ref8    in  varchar2 default null,
        p_ref9    in  varchar2 default null,
        p_ref10    in  varchar2 default null,
        p_attachment    in  blob default null,
        p_file_name    in  varchar2 default null,
        p_file_mimetyp    in  varchar2 default null,
        p_file_charset    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end gs_doc_attachments_api;
/

create or replace package body gs_doc_attachments_api
is

    procedure get_row (
        p_id        in  number,
        p_docno   out  number,
        p_doctyp   out  varchar2,
        p_refno   out  number,
        p_reftyp   out  varchar2,
        p_refdt   out  date,
        p_ref_page_no   out  number,
        p_reference   out  varchar2,
        p_ref1   out  varchar2,
        p_ref2   out  varchar2,
        p_ref3   out  varchar2,
        p_ref4   out  varchar2,
        p_ref5   out  varchar2,
        p_ref6   out  varchar2,
        p_ref7   out  varchar2,
        p_ref8   out  varchar2,
        p_ref9   out  varchar2,
        p_ref10   out  varchar2,
        p_attachment   out  blob,
        p_file_name   out  varchar2,
        p_file_mimetyp   out  varchar2,
        p_file_charset   out  varchar2,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from gs_doc_attachments where id = p_id) loop 
            p_docno := c1.docno;
            p_doctyp := c1.doctyp;
            p_refno := c1.refno;
            p_reftyp := c1.reftyp;
            p_refdt := c1.refdt;
            p_ref_page_no := c1.ref_page_no;
            p_reference := c1.reference;
            p_ref1 := c1.ref1;
            p_ref2 := c1.ref2;
            p_ref3 := c1.ref3;
            p_ref4 := c1.ref4;
            p_ref5 := c1.ref5;
            p_ref6 := c1.ref6;
            p_ref7 := c1.ref7;
            p_ref8 := c1.ref8;
            p_ref9 := c1.ref9;
            p_ref10 := c1.ref10;
            p_attachment := c1.attachment;
            p_file_name := c1.file_name;
            p_file_mimetyp := c1.file_mimetyp;
            p_file_charset := c1.file_charset;
            p_status := c1.status;
            p_attribute1 := c1.attribute1;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_docno    in  number default null,
        p_doctyp    in  varchar2 default null,
        p_refno    in  number default null,
        p_reftyp    in  varchar2 default null,
        p_refdt    in  date default null,
        p_ref_page_no    in  number default null,
        p_reference    in  varchar2 default null,
        p_ref1    in  varchar2 default null,
        p_ref2    in  varchar2 default null,
        p_ref3    in  varchar2 default null,
        p_ref4    in  varchar2 default null,
        p_ref5    in  varchar2 default null,
        p_ref6    in  varchar2 default null,
        p_ref7    in  varchar2 default null,
        p_ref8    in  varchar2 default null,
        p_ref9    in  varchar2 default null,
        p_ref10    in  varchar2 default null,
        p_attachment    in  blob default null,
        p_file_name    in  varchar2 default null,
        p_file_mimetyp    in  varchar2 default null,
        p_file_charset    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        insert into gs_doc_attachments ( 
            id,
            docno,
            doctyp,
            refno,
            reftyp,
            refdt,
            ref_page_no,
            reference,
            ref1,
            ref2,
            ref3,
            ref4,
            ref5,
            ref6,
            ref7,
            ref8,
            ref9,
            ref10,
            attachment,
            file_name,
            file_mimetyp,
            file_charset,
            status,
            attribute1,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10
        ) values ( 
            p_id,
            p_docno,
            p_doctyp,
            p_refno,
            p_reftyp,
            p_refdt,
            p_ref_page_no,
            p_reference,
            p_ref1,
            p_ref2,
            p_ref3,
            p_ref4,
            p_ref5,
            p_ref6,
            p_ref7,
            p_ref8,
            p_ref9,
            p_ref10,
            p_attachment,
            p_file_name,
            p_file_mimetyp,
            p_file_charset,
            p_status,
            p_attribute1,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_docno    in  number default null,
        p_doctyp    in  varchar2 default null,
        p_refno    in  number default null,
        p_reftyp    in  varchar2 default null,
        p_refdt    in  date default null,
        p_ref_page_no    in  number default null,
        p_reference    in  varchar2 default null,
        p_ref1    in  varchar2 default null,
        p_ref2    in  varchar2 default null,
        p_ref3    in  varchar2 default null,
        p_ref4    in  varchar2 default null,
        p_ref5    in  varchar2 default null,
        p_ref6    in  varchar2 default null,
        p_ref7    in  varchar2 default null,
        p_ref8    in  varchar2 default null,
        p_ref9    in  varchar2 default null,
        p_ref10    in  varchar2 default null,
        p_attachment    in  blob default null,
        p_file_name    in  varchar2 default null,
        p_file_mimetyp    in  varchar2 default null,
        p_file_charset    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        update  gs_doc_attachments set 
            id = p_id,
            docno = p_docno
,
            doctyp = p_doctyp
,
            refno = p_refno
,
            reftyp = p_reftyp
,
            refdt = p_refdt
,
            ref_page_no = p_ref_page_no
,
            reference = p_reference
,
            ref1 = p_ref1
,
            ref2 = p_ref2
,
            ref3 = p_ref3
,
            ref4 = p_ref4
,
            ref5 = p_ref5
,
            ref6 = p_ref6
,
            ref7 = p_ref7
,
            ref8 = p_ref8
,
            ref9 = p_ref9
,
            ref10 = p_ref10
,
            attachment = p_attachment
,
            file_name = p_file_name
,
            file_mimetyp = p_file_mimetyp
,
            file_charset = p_file_charset
,
            status = p_status
,
            attribute1 = p_attribute1
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from gs_doc_attachments where id = p_id;
    end delete_row;
end gs_doc_attachments_api;
/

-- Grant select, insert, update, delete access to GSAPEX schema for GS_DOC_ATTACHMENTS table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.GS_DOC_ATTACHMENTS TO gsapex;
/
-- Grant execute privilege on gs_doc_attachments_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.gs_doc_attachments_api TO gsapex;

-- Generated by Quick SQL 1.2.9 5/28/2024, 5:43:34 PM

/*
GS_DOC_ATTACHMENTS
    DOCNO	        NUM,
    DOCTYP	        VC(50),
    REFNO	        NUM,
    REFTYP	        VC(50),
    REFDT	        DATE,	
    REF_PAGE_NO	    NUM,	
    REFERENCE	    VC(100),	
    REF1	        VC(100),	
    REF2	        VC(100),	
    REF3	        VC(100),	
    REF4	        VC(100),	
    REF5	        VC(100),	
    REF6	        VC(100),	
    REF7	        VC(100),	
    REF8	        VC(100),	
    REF9	        VC(100),	
    REF10	        VC(100),	
    ATTACHMENT	    BLOB,	
    FILE_NAME	    VC(500),	
    FILE_MIMETYP	VC(500),	
    FILE_CHARSET	VC(500),	
    STATUS	        VC(50),	
    ATTRIBUTE1	    VC(100),	
    ATTRIBUTE2	    VC(100),	
    ATTRIBUTE3	    VC(100),	
    ATTRIBUTE4	    VC(100),	
    ATTRIBUTE5	    VC(100),	
    ATTRIBUTE6	    VC(100),	
    ATTRIBUTE7	    VC(100),	
    ATTRIBUTE8	    VC(100),	
    ATTRIBUTE9	    VC(100),	
    ATTRIBUTE10	    VC(100)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/