-- create tables

create table SOAPP_SUPPLIER_TAX (
    id                   number generated by default on null as identity
                         constraint soapp_supplier_tax_id_pk primary key,
    TAX_ID               number,
    COMPANY_NAME         varchar2(100 char),
    TAX_PAYER_ID         varchar2(100 char),
    ATTACHMENT_ID        number,
    COUNTRY              varchar2(100 char),
    VENDOR_ID            number,
    REG_REQUEST_ID       number,
    CH_REG_REQUEST_ID    number,
    STATUS               varchar2(50 char),
    ATTRIBUTE1           varchar2(100 char),
    ATTRIBUTE2           varchar2(100 char),
    ATTRIBUTE3           varchar2(100 char),
    ATTRIBUTE4           varchar2(100 char),
    ATTRIBUTE5           varchar2(100 char),
    ATTRIBUTE6           varchar2(100 char),
    ATTRIBUTE7           varchar2(100 char),
    ATTRIBUTE8           varchar2(100 char),
    ATTRIBUTE9           varchar2(100 char),
    ATTRIBUTE10          varchar2(100 char),
    CREATION_DATE        date not null,
    CREATED_BY           varchar2(255 char) not null,
    LAST_UPDATED_DATE    date not null,
    LAST_UPDATED_BY      varchar2(255 char) not null
);



-- triggers
create or replace trigger soapp_supplier_tax_biu
    before insert or update
    on soapp_supplier_tax
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end soapp_supplier_tax_biu;
/


-- APIs
create or replace package soapp_supplier_tax_api
is

    procedure get_row (
        p_id        in  number,
        p_tax_id   out  number,
        p_company_name   out  varchar2,
        p_tax_payer_id   out  varchar2,
        p_attachment_id   out  number,
        p_country   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_tax_id    in  number default null,
        p_company_name    in  varchar2 default null,
        p_tax_payer_id    in  varchar2 default null,
        p_attachment_id    in  number default null,
        p_country    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_tax_id    in  number default null,
        p_company_name    in  varchar2 default null,
        p_tax_payer_id    in  varchar2 default null,
        p_attachment_id    in  number default null,
        p_country    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end soapp_supplier_tax_api;
/

create or replace package body soapp_supplier_tax_api
is

    procedure get_row (
        p_id        in  number,
        p_tax_id   out  number,
        p_company_name   out  varchar2,
        p_tax_payer_id   out  varchar2,
        p_attachment_id   out  number,
        p_country   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from soapp_supplier_tax where id = p_id) loop 
            p_tax_id := c1.tax_id;
            p_company_name := c1.company_name;
            p_tax_payer_id := c1.tax_payer_id;
            p_attachment_id := c1.attachment_id;
            p_country := c1.country;
            p_vendor_id := c1.vendor_id;
            p_reg_request_id := c1.reg_request_id;
            p_ch_reg_request_id := c1.ch_reg_request_id;
            p_status := c1.status;
            p_attribute1 := c1.attribute1;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_tax_id    in  number default null,
        p_company_name    in  varchar2 default null,
        p_tax_payer_id    in  varchar2 default null,
        p_attachment_id    in  number default null,
        p_country    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        insert into soapp_supplier_tax ( 
            id,
            tax_id,
            company_name,
            tax_payer_id,
            attachment_id,
            country,
            vendor_id,
            reg_request_id,
            ch_reg_request_id,
            status,
            attribute1,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10
        ) values ( 
            p_id,
            p_tax_id,
            p_company_name,
            p_tax_payer_id,
            p_attachment_id,
            p_country,
            p_vendor_id,
            p_reg_request_id,
            p_ch_reg_request_id,
            p_status,
            p_attribute1,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_tax_id    in  number default null,
        p_company_name    in  varchar2 default null,
        p_tax_payer_id    in  varchar2 default null,
        p_attachment_id    in  number default null,
        p_country    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        update  soapp_supplier_tax set 
            id = p_id,
            tax_id = p_tax_id
,
            company_name = p_company_name
,
            tax_payer_id = p_tax_payer_id
,
            attachment_id = p_attachment_id
,
            country = p_country
,
            vendor_id = p_vendor_id
,
            reg_request_id = p_reg_request_id
,
            ch_reg_request_id = p_ch_reg_request_id
,
            status = p_status
,
            attribute1 = p_attribute1
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from soapp_supplier_tax where id = p_id;
    end delete_row;
end soapp_supplier_tax_api;
/
-- Grant select, insert, update, delete access to GSAPEX schema for soapp_supplier_tax table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.soapp_supplier_tax TO gsapex;
/
-- Grant execute privilege on soapp_supplier_tax_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.soapp_supplier_tax_api TO gsapex;
/
-- Create synonyms for easier access in GSAPEX schema
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_tax FOR GSSOAPP.soapp_supplier_tax;
/
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_tax_api FOR GSSOAPP.soapp_supplier_tax_api;
-- Generated by Quick SQL 1.2.9 5/28/2024, 5:42:25 PM

/*
SOAPP_SUPPLIER_TAX
    TAX_ID				NUMBER	
    COMPANY_NAME		vc(100)
    TAX_PAYER_ID		vc(100)
    ATTACHMENT_ID		NUMBER	
    COUNTRY				vc(100)
    VENDOR_ID			NUMBER	
    REG_REQUEST_ID		NUMBER
    CH_REG_REQUEST_ID	NUMBER	
    STATUS				vc(50)	
    ATTRIBUTE1			vc(100)
    ATTRIBUTE2			vc(100)
    ATTRIBUTE3			vc(100)
    ATTRIBUTE4			vc(100)
    ATTRIBUTE5			vc(100)
    ATTRIBUTE6			vc(100)
    ATTRIBUTE7			vc(100)
    ATTRIBUTE8			vc(100)
    ATTRIBUTE9			vc(100)
    ATTRIBUTE10			vc(100)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/