-- create tables

create table SOAPP_SUPPLIER_PAYMENTS (
    id                       number generated by default on null as identity
                             constraint soapp_supplier_payments_id_pk primary key,
    PAYMENT_ID               number,
    PROFILE_ID               number,
    INVOICE_CURRENCY         varchar2(100 char),
    PAYMENT_CURRENCY         varchar2(100 char),
    BANK_NAME                varchar2(100 char),
    BANK_ACCT_HOLDER_NAME    varchar2(100 char),
    BANK_ACCT_NUMBER         varchar2(100 char),
    REMITTANCE_EMAIL         varchar2(100 char),
    PAYMENT_METHOD           varchar2(100 char),
    BANK_ROUTING_NUMBER      varchar2(100 char),
    SORT_CODE                varchar2(100 char),
    IBAN                     varchar2(100 char),
    SWIFT_CODE               varchar2(100 char),
    BIC_CODE                 varchar2(100 char),
    VENDOR_ID                number,
    REG_REQUEST_ID           number,
    CH_REG_REQUEST_ID        number,
    STATUS                   varchar2(50 char),
    ATTRIBUTE1               varchar2(100 char),
    ATTRIBUTE2               varchar2(100 char),
    ATTRIBUTE3               varchar2(100 char),
    ATTRIBUTE4               varchar2(100 char),
    ATTRIBUTE5               varchar2(100 char),
    ATTRIBUTE6               varchar2(100 char),
    ATTRIBUTE7               varchar2(100 char),
    ATTRIBUTE8               varchar2(100 char),
    ATTRIBUTE9               varchar2(100 char),
    ATTRIBUTE10              varchar2(100 char),
    CREATION_DATE            date not null,
    CREATED_BY               varchar2(255 char) not null,
    LAST_UPDATED_DATE        date not null,
    LAST_UPDATED_BY          varchar2(255 char) not null
);



-- triggers
create or replace trigger soapp_supplier_payments_biu
    before insert or update
    on soapp_supplier_payments
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end soapp_supplier_payments_biu;
/


-- APIs
create or replace package soapp_supplier_payments_api
is

    procedure get_row (
        p_id        in  number,
        p_payment_id   out  number,
        p_profile_id   out  number,
        p_invoice_currency   out  varchar2,
        p_payment_currency   out  varchar2,
        p_bank_name   out  varchar2,
        p_bank_acct_holder_name   out  varchar2,
        p_bank_acct_number   out  varchar2,
        p_remittance_email   out  varchar2,
        p_payment_method   out  varchar2,
        p_bank_routing_number   out  varchar2,
        p_sort_code   out  varchar2,
        p_iban   out  varchar2,
        p_swift_code   out  varchar2,
        p_bic_code   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_payment_id    in  number default null,
        p_profile_id    in  number default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_bank_name    in  varchar2 default null,
        p_bank_acct_holder_name    in  varchar2 default null,
        p_bank_acct_number    in  varchar2 default null,
        p_remittance_email    in  varchar2 default null,
        p_payment_method    in  varchar2 default null,
        p_bank_routing_number    in  varchar2 default null,
        p_sort_code    in  varchar2 default null,
        p_iban    in  varchar2 default null,
        p_swift_code    in  varchar2 default null,
        p_bic_code    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_payment_id    in  number default null,
        p_profile_id    in  number default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_bank_name    in  varchar2 default null,
        p_bank_acct_holder_name    in  varchar2 default null,
        p_bank_acct_number    in  varchar2 default null,
        p_remittance_email    in  varchar2 default null,
        p_payment_method    in  varchar2 default null,
        p_bank_routing_number    in  varchar2 default null,
        p_sort_code    in  varchar2 default null,
        p_iban    in  varchar2 default null,
        p_swift_code    in  varchar2 default null,
        p_bic_code    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end soapp_supplier_payments_api;
/

create or replace package body soapp_supplier_payments_api
is

    procedure get_row (
        p_id        in  number,
        p_payment_id   out  number,
        p_profile_id   out  number,
        p_invoice_currency   out  varchar2,
        p_payment_currency   out  varchar2,
        p_bank_name   out  varchar2,
        p_bank_acct_holder_name   out  varchar2,
        p_bank_acct_number   out  varchar2,
        p_remittance_email   out  varchar2,
        p_payment_method   out  varchar2,
        p_bank_routing_number   out  varchar2,
        p_sort_code   out  varchar2,
        p_iban   out  varchar2,
        p_swift_code   out  varchar2,
        p_bic_code   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from soapp_supplier_payments where id = p_id) loop 
            p_payment_id := c1.payment_id;
            p_profile_id := c1.profile_id;
            p_invoice_currency := c1.invoice_currency;
            p_payment_currency := c1.payment_currency;
            p_bank_name := c1.bank_name;
            p_bank_acct_holder_name := c1.bank_acct_holder_name;
            p_bank_acct_number := c1.bank_acct_number;
            p_remittance_email := c1.remittance_email;
            p_payment_method := c1.payment_method;
            p_bank_routing_number := c1.bank_routing_number;
            p_sort_code := c1.sort_code;
            p_iban := c1.iban;
            p_swift_code := c1.swift_code;
            p_bic_code := c1.bic_code;
            p_vendor_id := c1.vendor_id;
            p_reg_request_id := c1.reg_request_id;
            p_ch_reg_request_id := c1.ch_reg_request_id;
            p_status := c1.status;
            p_attribute1 := c1.attribute1;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_payment_id    in  number default null,
        p_profile_id    in  number default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_bank_name    in  varchar2 default null,
        p_bank_acct_holder_name    in  varchar2 default null,
        p_bank_acct_number    in  varchar2 default null,
        p_remittance_email    in  varchar2 default null,
        p_payment_method    in  varchar2 default null,
        p_bank_routing_number    in  varchar2 default null,
        p_sort_code    in  varchar2 default null,
        p_iban    in  varchar2 default null,
        p_swift_code    in  varchar2 default null,
        p_bic_code    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        insert into soapp_supplier_payments ( 
            id,
            payment_id,
            profile_id,
            invoice_currency,
            payment_currency,
            bank_name,
            bank_acct_holder_name,
            bank_acct_number,
            remittance_email,
            payment_method,
            bank_routing_number,
            sort_code,
            iban,
            swift_code,
            bic_code,
            vendor_id,
            reg_request_id,
            ch_reg_request_id,
            status,
            attribute1,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10
        ) values ( 
            p_id,
            p_payment_id,
            p_profile_id,
            p_invoice_currency,
            p_payment_currency,
            p_bank_name,
            p_bank_acct_holder_name,
            p_bank_acct_number,
            p_remittance_email,
            p_payment_method,
            p_bank_routing_number,
            p_sort_code,
            p_iban,
            p_swift_code,
            p_bic_code,
            p_vendor_id,
            p_reg_request_id,
            p_ch_reg_request_id,
            p_status,
            p_attribute1,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_payment_id    in  number default null,
        p_profile_id    in  number default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_bank_name    in  varchar2 default null,
        p_bank_acct_holder_name    in  varchar2 default null,
        p_bank_acct_number    in  varchar2 default null,
        p_remittance_email    in  varchar2 default null,
        p_payment_method    in  varchar2 default null,
        p_bank_routing_number    in  varchar2 default null,
        p_sort_code    in  varchar2 default null,
        p_iban    in  varchar2 default null,
        p_swift_code    in  varchar2 default null,
        p_bic_code    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        update  soapp_supplier_payments set 
            id = p_id,
            payment_id = p_payment_id
,
            profile_id = p_profile_id
,
            invoice_currency = p_invoice_currency
,
            payment_currency = p_payment_currency
,
            bank_name = p_bank_name
,
            bank_acct_holder_name = p_bank_acct_holder_name
,
            bank_acct_number = p_bank_acct_number
,
            remittance_email = p_remittance_email
,
            payment_method = p_payment_method
,
            bank_routing_number = p_bank_routing_number
,
            sort_code = p_sort_code
,
            iban = p_iban
,
            swift_code = p_swift_code
,
            bic_code = p_bic_code
,
            vendor_id = p_vendor_id
,
            reg_request_id = p_reg_request_id
,
            ch_reg_request_id = p_ch_reg_request_id
,
            status = p_status
,
            attribute1 = p_attribute1
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from soapp_supplier_payments where id = p_id;
    end delete_row;
end soapp_supplier_payments_api;
/

-- Grant select, insert, update, delete access to GSAPEX schema for soapp_supplier_payments table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.soapp_supplier_payments TO gsapex;
/
-- Grant execute privilege on soapp_supplier_payments_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.soapp_supplier_payments_api TO gsapex;
/
-- Create synonyms for easier access in GSAPEX schema
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_payments FOR GSSOAPP.soapp_supplier_payments;
/
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_payments_api FOR GSSOAPP.soapp_supplier_payments_api;
-- Generated by Quick SQL 1.2.9 5/28/2024, 5:38:38 PM

/*
SOAPP_SUPPLIER_PAYMENTS

    PAYMENT_ID	            NUMBER,	
 	PROFILE_ID	            NUMBER,
 	INVOICE_CURRENCY	    vc(100),	
 	PAYMENT_CURRENCY	    vc(100),	
 	BANK_NAME	            vc(100),	
 	BANK_ACCT_HOLDER_NAME	vc(100),	
 	BANK_ACCT_NUMBER	    vc(100),	
 	REMITTANCE_EMAIL	    vc(100),	
 	PAYMENT_METHOD	        vc(100),	
 	BANK_ROUTING_NUMBER	    vc(100),	
 	SORT_CODE	            vc(100),	
 	IBAN	                vc(100),	
 	SWIFT_CODE	            vc(100),	
 	BIC_CODE	            vc(100),	
 	VENDOR_ID	            NUM,	
 	REG_REQUEST_ID	        NUM,	
 	CH_REG_REQUEST_ID	    NUM,	
 	STATUS	                vc(50),	
 	ATTRIBUTE1	            vc(100),	
 	ATTRIBUTE2	            vc(100),	
 	ATTRIBUTE3	            vc(100),	
 	ATTRIBUTE4	            vc(100),	
 	ATTRIBUTE5	            vc(100),	
 	ATTRIBUTE6	            vc(100),	
 	ATTRIBUTE7	            vc(100),	
 	ATTRIBUTE8	            vc(100),	
 	ATTRIBUTE9	            vc(100),	
 	ATTRIBUTE10	            vc(100)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/