-- create tables

create table SOAPP_REG_SUPPLIER_CONTACTS (
    id                   number generated by default on null as identity
                         constraint soapp_reg_supplier_contacts_id_pk primary key,
    CONTACT_ID           number,
    PROFILE_ID           number,
    FIRST_NAME           varchar2(100 char),
    LAST_NAME            varchar2(100 char),
    EMAIL                varchar2(100 char),
    PHONE                varchar2(100 char),
    FAX                  varchar2(100 char),
    LANGUAGE             varchar2(100 char),
    PRIMARY_FLAG         varchar2(100 char),
    CONTACT_TYPE         varchar2(100 char),
    VENDOR_ID            number,
    REG_REQUEST_ID       number,
    CH_REG_REQUEST_ID    number,
    STATUS               varchar2(100 char),
    ATTRIBUTE1           varchar2(100 char),
    ATTRIBUTE2           varchar2(100 char),
    ATTRIBUTE3           varchar2(100 char),
    ATTRIBUTE4           varchar2(100 char),
    ATTRIBUTE5           varchar2(100 char),
    ATTRIBUTE6           varchar2(100 char),
    ATTRIBUTE7           varchar2(100 char),
    ATTRIBUTE8           varchar2(100 char),
    ATTRIBUTE9           varchar2(100 char),
    ATTRIBUTE10          varchar2(100 char),
    CREATION_DATE        date not null,
    CREATED_BY           varchar2(255 char) not null,
    LAST_UPDATED_DATE    date not null,
    LAST_UPDATED_BY      varchar2(255 char) not null
);



-- triggers
create or replace trigger soapp_reg_supplier_contacts_biu
    before insert or update
    on soapp_reg_supplier_contacts
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end soapp_reg_supplier_contacts_biu;
/


-- APIs
create or replace package soapp_reg_supplier_contacts_api
is

    procedure get_row (
        p_id        in  number,
        p_contact_id   out  number,
        p_profile_id   out  number,
        p_first_name   out  varchar2,
        p_last_name   out  varchar2,
        p_email   out  varchar2,
        p_phone   out  varchar2,
        p_fax   out  varchar2,
        p_language   out  varchar2,
        p_primary_flag   out  varchar2,
        p_contact_type   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_contact_id    in  number default null,
        p_profile_id    in  number default null,
        p_first_name    in  varchar2 default null,
        p_last_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_phone    in  varchar2 default null,
        p_fax    in  varchar2 default null,
        p_language    in  varchar2 default null,
        p_primary_flag    in  varchar2 default null,
        p_contact_type    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_contact_id    in  number default null,
        p_profile_id    in  number default null,
        p_first_name    in  varchar2 default null,
        p_last_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_phone    in  varchar2 default null,
        p_fax    in  varchar2 default null,
        p_language    in  varchar2 default null,
        p_primary_flag    in  varchar2 default null,
        p_contact_type    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end soapp_reg_supplier_contacts_api;
/

create or replace package body soapp_reg_supplier_contacts_api
is

    procedure get_row (
        p_id        in  number,
        p_contact_id   out  number,
        p_profile_id   out  number,
        p_first_name   out  varchar2,
        p_last_name   out  varchar2,
        p_email   out  varchar2,
        p_phone   out  varchar2,
        p_fax   out  varchar2,
        p_language   out  varchar2,
        p_primary_flag   out  varchar2,
        p_contact_type   out  varchar2,
        p_vendor_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from soapp_reg_supplier_contacts where id = p_id) loop 
            p_contact_id := c1.contact_id;
            p_profile_id := c1.profile_id;
            p_first_name := c1.first_name;
            p_last_name := c1.last_name;
            p_email := c1.email;
            p_phone := c1.phone;
            p_fax := c1.fax;
            p_language := c1.language;
            p_primary_flag := c1.primary_flag;
            p_contact_type := c1.contact_type;
            p_vendor_id := c1.vendor_id;
            p_reg_request_id := c1.reg_request_id;
            p_ch_reg_request_id := c1.ch_reg_request_id;
            p_status := c1.status;
            p_attribute1 := c1.attribute1;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_contact_id    in  number default null,
        p_profile_id    in  number default null,
        p_first_name    in  varchar2 default null,
        p_last_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_phone    in  varchar2 default null,
        p_fax    in  varchar2 default null,
        p_language    in  varchar2 default null,
        p_primary_flag    in  varchar2 default null,
        p_contact_type    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        insert into soapp_reg_supplier_contacts ( 
            id,
            contact_id,
            profile_id,
            first_name,
            last_name,
            email,
            phone,
            fax,
            language,
            primary_flag,
            contact_type,
            vendor_id,
            reg_request_id,
            ch_reg_request_id,
            status,
            attribute1,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10
        ) values ( 
            p_id,
            p_contact_id,
            p_profile_id,
            p_first_name,
            p_last_name,
            p_email,
            p_phone,
            p_fax,
            p_language,
            p_primary_flag,
            p_contact_type,
            p_vendor_id,
            p_reg_request_id,
            p_ch_reg_request_id,
            p_status,
            p_attribute1,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_contact_id    in  number default null,
        p_profile_id    in  number default null,
        p_first_name    in  varchar2 default null,
        p_last_name    in  varchar2 default null,
        p_email    in  varchar2 default null,
        p_phone    in  varchar2 default null,
        p_fax    in  varchar2 default null,
        p_language    in  varchar2 default null,
        p_primary_flag    in  varchar2 default null,
        p_contact_type    in  varchar2 default null,
        p_vendor_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null
    )
    is 
    begin 
        update  soapp_reg_supplier_contacts set 
            id = p_id,
            contact_id = p_contact_id
,
            profile_id = p_profile_id
,
            first_name = p_first_name
,
            last_name = p_last_name
,
            email = p_email
,
            phone = p_phone
,
            fax = p_fax
,
            language = p_language
,
            primary_flag = p_primary_flag
,
            contact_type = p_contact_type
,
            vendor_id = p_vendor_id
,
            reg_request_id = p_reg_request_id
,
            ch_reg_request_id = p_ch_reg_request_id
,
            status = p_status
,
            attribute1 = p_attribute1
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from soapp_reg_supplier_contacts where id = p_id;
    end delete_row;
end soapp_reg_supplier_contacts_api;
/
-- Grant select, insert, update, delete access to GSAPEX schema for SOAPP_REG_SUPPLIER_CONTACTS table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.SOAPP_REG_SUPPLIER_CONTACTS TO gsapex;
/
-- Grant execute privilege on soapp_reg_supplier_contacts_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.soapp_reg_supplier_contacts_api TO gsapex;
/
-- Create synonyms for easier access in GSAPEX schema
CREATE OR REPLACE SYNONYM gsapex.SOAPP_REG_SUPPLIER_CONTACTS FOR GSSOAPP.SOAPP_REG_SUPPLIER_CONTACTS;
/
CREATE OR REPLACE SYNONYM gsapex.soapp_reg_supplier_contacts_api FOR GSSOAPP.soapp_reg_supplier_contacts_api;
-- Generated by Quick SQL 1.2.9 5/30/2024, 1:30:41 PM
-- Generated by Quick SQL 1.2.9 5/30/2024, 1:30:02 PM

/*
SOAPP_REG_SUPPLIER_CONTACTS
    CONTACT_ID num,
    PROFILE_ID num,
    FIRST_NAME VC(100),
    LAST_NAME VC(100),
    EMAIL	  VC(100),  	
    PHONE	VC(100),		
    FAX		VC(100),		
    LANGUAGE VC(100),		
    PRIMARY_FLAG VC(100),	
    CONTACT_TYPE VC(100),
    VENDOR_ID	   NUM,	
    REG_REQUEST_ID	NUM,
    CH_REG_REQUEST_ID NUM,
    STATUS		VC(100),
    ATTRIBUTE1	VC(100),	
    ATTRIBUTE2	VC(100),	
    ATTRIBUTE3	VC(100),	
    ATTRIBUTE4	VC(100),	
    ATTRIBUTE5	VC(100),	
    ATTRIBUTE6	VC(100),	
    ATTRIBUTE7	VC(100),	
    ATTRIBUTE8	VC(100),	
    ATTRIBUTE9	VC(100),	
    ATTRIBUTE10 VC(100),

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/