-- create tables

create table SOAPP_SUPPLIERS (
    id                         number generated by default on null as identity
                               constraint soapp_suppliers_id_pk primary key,
    REG_REQUEST_ID             number,
    VENDOR_ID                  number,
    EXEMPT_FLAG                varchar2(50 char),
    REQUESTOR_ID               number,
    STATUS                     varchar2(50 char),
    BU_ID                      number,
    CH_REG_REQUEST_ID          number,
    PRIORITY                   number,
    SUPPLIER_CATEGORY          varchar2(100 char),
    COUNTRY                    varchar2(100 char),
    GREYSTAR_LOB               varchar2(100 char),
    COMPLIANCE_TYPE            varchar2(100 char),
    BU_NAME                    varchar2(100 char),
    TEAM_MEMBER_TITLE          varchar2(100 char),
    PAY_GROUP                  varchar2(100 char),
    PAYMENT_TERMS              varchar2(100 char),
    INVOICE_CURRENCY           varchar2(100 char),
    PAYMENT_CURRENCY           varchar2(100 char),
    REQUESTOR_NAME             varchar2(100 char),
    EXTERNAL_SYSTEM            varchar2(100 char),
    EXTERNAL_SYS_IDENTIFIER    varchar2(100 char),
    VENDOR_CODE                varchar2(100 char),
    DOC_TYPE                   varchar2(100 char),
    ATTRIBUTE2                 varchar2(100 char),
    ATTRIBUTE3                 varchar2(100 char),
    ATTRIBUTE4                 varchar2(100 char),
    ATTRIBUTE5                 varchar2(100 char),
    ATTRIBUTE6                 varchar2(100 char),
    ATTRIBUTE7                 varchar2(100 char),
    ATTRIBUTE8                 varchar2(100 char),
    ATTRIBUTE9                 varchar2(100 char),
    ATTRIBUTE10                varchar2(100 char),
    INACTIVE_DATE              date,
    MESSAGE                    varchar2(255 char),
    SOURCE                     varchar2(100 char),
    CREATION_DATE              date not null,
    CREATED_BY                 varchar2(255 char) not null,
    LAST_UPDATED_DATE          date not null,
    LAST_UPDATED_BY            varchar2(255 char) not null
);



-- triggers
create or replace trigger soapp_suppliers_biu
    before insert or update
    on soapp_suppliers
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end soapp_suppliers_biu;
/


-- APIs
create or replace package soapp_suppliers_api
is

    procedure get_row (
        p_id        in  number,
        p_reg_request_id   out  number,
        p_vendor_id   out  number,
        p_exempt_flag   out  varchar2,
        p_requestor_id   out  number,
        p_status   out  varchar2,
        p_bu_id   out  number,
        p_ch_reg_request_id   out  number,
        p_priority   out  number,
        p_supplier_category   out  varchar2,
        p_country   out  varchar2,
        p_greystar_lob   out  varchar2,
        p_compliance_type   out  varchar2,
        p_bu_name   out  varchar2,
        p_team_member_title   out  varchar2,
        p_pay_group   out  varchar2,
        p_payment_terms   out  varchar2,
        p_invoice_currency   out  varchar2,
        p_payment_currency   out  varchar2,
        p_requestor_name   out  varchar2,
        p_external_system   out  varchar2,
        p_external_sys_identifier   out  varchar2,
        p_vendor_code   out  varchar2,
        p_doc_type   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2,
        p_inactive_date   out  date,
        p_message   out  varchar2,
        p_source   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_reg_request_id    in  number default null,
        p_vendor_id    in  number default null,
        p_exempt_flag    in  varchar2 default null,
        p_requestor_id    in  number default null,
        p_status    in  varchar2 default null,
        p_bu_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_priority    in  number default null,
        p_supplier_category    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_greystar_lob    in  varchar2 default null,
        p_compliance_type    in  varchar2 default null,
        p_bu_name    in  varchar2 default null,
        p_team_member_title    in  varchar2 default null,
        p_pay_group    in  varchar2 default null,
        p_payment_terms    in  varchar2 default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_requestor_name    in  varchar2 default null,
        p_external_system    in  varchar2 default null,
        p_external_sys_identifier    in  varchar2 default null,
        p_vendor_code    in  varchar2 default null,
        p_doc_type    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_inactive_date    in  date default null,
        p_message    in  varchar2 default null,
        p_source    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_reg_request_id    in  number default null,
        p_vendor_id    in  number default null,
        p_exempt_flag    in  varchar2 default null,
        p_requestor_id    in  number default null,
        p_status    in  varchar2 default null,
        p_bu_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_priority    in  number default null,
        p_supplier_category    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_greystar_lob    in  varchar2 default null,
        p_compliance_type    in  varchar2 default null,
        p_bu_name    in  varchar2 default null,
        p_team_member_title    in  varchar2 default null,
        p_pay_group    in  varchar2 default null,
        p_payment_terms    in  varchar2 default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_requestor_name    in  varchar2 default null,
        p_external_system    in  varchar2 default null,
        p_external_sys_identifier    in  varchar2 default null,
        p_vendor_code    in  varchar2 default null,
        p_doc_type    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_inactive_date    in  date default null,
        p_message    in  varchar2 default null,
        p_source    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end soapp_suppliers_api;
/

create or replace package body soapp_suppliers_api
is

    procedure get_row (
        p_id        in  number,
        p_reg_request_id   out  number,
        p_vendor_id   out  number,
        p_exempt_flag   out  varchar2,
        p_requestor_id   out  number,
        p_status   out  varchar2,
        p_bu_id   out  number,
        p_ch_reg_request_id   out  number,
        p_priority   out  number,
        p_supplier_category   out  varchar2,
        p_country   out  varchar2,
        p_greystar_lob   out  varchar2,
        p_compliance_type   out  varchar2,
        p_bu_name   out  varchar2,
        p_team_member_title   out  varchar2,
        p_pay_group   out  varchar2,
        p_payment_terms   out  varchar2,
        p_invoice_currency   out  varchar2,
        p_payment_currency   out  varchar2,
        p_requestor_name   out  varchar2,
        p_external_system   out  varchar2,
        p_external_sys_identifier   out  varchar2,
        p_vendor_code   out  varchar2,
        p_doc_type   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2,
        p_inactive_date   out  date,
        p_message   out  varchar2,
        p_source   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from soapp_suppliers where id = p_id) loop 
            p_reg_request_id := c1.reg_request_id;
            p_vendor_id := c1.vendor_id;
            p_exempt_flag := c1.exempt_flag;
            p_requestor_id := c1.requestor_id;
            p_status := c1.status;
            p_bu_id := c1.bu_id;
            p_ch_reg_request_id := c1.ch_reg_request_id;
            p_priority := c1.priority;
            p_supplier_category := c1.supplier_category;
            p_country := c1.country;
            p_greystar_lob := c1.greystar_lob;
            p_compliance_type := c1.compliance_type;
            p_bu_name := c1.bu_name;
            p_team_member_title := c1.team_member_title;
            p_pay_group := c1.pay_group;
            p_payment_terms := c1.payment_terms;
            p_invoice_currency := c1.invoice_currency;
            p_payment_currency := c1.payment_currency;
            p_requestor_name := c1.requestor_name;
            p_external_system := c1.external_system;
            p_external_sys_identifier := c1.external_sys_identifier;
            p_vendor_code := c1.vendor_code;
            p_doc_type := c1.doc_type;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;
            p_inactive_date := c1.inactive_date;
            p_message := c1.message;
            p_source := c1.source;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_reg_request_id    in  number default null,
        p_vendor_id    in  number default null,
        p_exempt_flag    in  varchar2 default null,
        p_requestor_id    in  number default null,
        p_status    in  varchar2 default null,
        p_bu_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_priority    in  number default null,
        p_supplier_category    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_greystar_lob    in  varchar2 default null,
        p_compliance_type    in  varchar2 default null,
        p_bu_name    in  varchar2 default null,
        p_team_member_title    in  varchar2 default null,
        p_pay_group    in  varchar2 default null,
        p_payment_terms    in  varchar2 default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_requestor_name    in  varchar2 default null,
        p_external_system    in  varchar2 default null,
        p_external_sys_identifier    in  varchar2 default null,
        p_vendor_code    in  varchar2 default null,
        p_doc_type    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_inactive_date    in  date default null,
        p_message    in  varchar2 default null,
        p_source    in  varchar2 default null
    )
    is 
    begin 
        insert into soapp_suppliers ( 
            id,
            reg_request_id,
            vendor_id,
            exempt_flag,
            requestor_id,
            status,
            bu_id,
            ch_reg_request_id,
            priority,
            supplier_category,
            country,
            greystar_lob,
            compliance_type,
            bu_name,
            team_member_title,
            pay_group,
            payment_terms,
            invoice_currency,
            payment_currency,
            requestor_name,
            external_system,
            external_sys_identifier,
            vendor_code,
            doc_type,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10,
            inactive_date,
            message,
            source
        ) values ( 
            p_id,
            p_reg_request_id,
            p_vendor_id,
            p_exempt_flag,
            p_requestor_id,
            p_status,
            p_bu_id,
            p_ch_reg_request_id,
            p_priority,
            p_supplier_category,
            p_country,
            p_greystar_lob,
            p_compliance_type,
            p_bu_name,
            p_team_member_title,
            p_pay_group,
            p_payment_terms,
            p_invoice_currency,
            p_payment_currency,
            p_requestor_name,
            p_external_system,
            p_external_sys_identifier,
            p_vendor_code,
            p_doc_type,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10,
            p_inactive_date,
            p_message,
            p_source
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_reg_request_id    in  number default null,
        p_vendor_id    in  number default null,
        p_exempt_flag    in  varchar2 default null,
        p_requestor_id    in  number default null,
        p_status    in  varchar2 default null,
        p_bu_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_priority    in  number default null,
        p_supplier_category    in  varchar2 default null,
        p_country    in  varchar2 default null,
        p_greystar_lob    in  varchar2 default null,
        p_compliance_type    in  varchar2 default null,
        p_bu_name    in  varchar2 default null,
        p_team_member_title    in  varchar2 default null,
        p_pay_group    in  varchar2 default null,
        p_payment_terms    in  varchar2 default null,
        p_invoice_currency    in  varchar2 default null,
        p_payment_currency    in  varchar2 default null,
        p_requestor_name    in  varchar2 default null,
        p_external_system    in  varchar2 default null,
        p_external_sys_identifier    in  varchar2 default null,
        p_vendor_code    in  varchar2 default null,
        p_doc_type    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_inactive_date    in  date default null,
        p_message    in  varchar2 default null,
        p_source    in  varchar2 default null
    )
    is 
    begin 
        update  soapp_suppliers set 
            id = p_id,
            reg_request_id = p_reg_request_id
,
            vendor_id = p_vendor_id
,
            exempt_flag = p_exempt_flag
,
            requestor_id = p_requestor_id
,
            status = p_status
,
            bu_id = p_bu_id
,
            ch_reg_request_id = p_ch_reg_request_id
,
            priority = p_priority
,
            supplier_category = p_supplier_category
,
            country = p_country
,
            greystar_lob = p_greystar_lob
,
            compliance_type = p_compliance_type
,
            bu_name = p_bu_name
,
            team_member_title = p_team_member_title
,
            pay_group = p_pay_group
,
            payment_terms = p_payment_terms
,
            invoice_currency = p_invoice_currency
,
            payment_currency = p_payment_currency
,
            requestor_name = p_requestor_name
,
            external_system = p_external_system
,
            external_sys_identifier = p_external_sys_identifier
,
            vendor_code = p_vendor_code
,
            doc_type = p_doc_type
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
,
            inactive_date = p_inactive_date
,
            message = p_message
,
            source = p_source
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from soapp_suppliers where id = p_id;
    end delete_row;
end soapp_suppliers_api;
/
-- Grant select, insert, update, delete access to GSAPEX schema for soapp_suppliers table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.soapp_suppliers TO gsapex;
/
-- Grant execute privilege on soapp_suppliers_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.soapp_suppliers_api TO gsapex;
-- Generated by Quick SQL 1.2.9 5/28/2024, 10:05:32 PM

/*
SOAPP_SUPPLIERS
    REG_REQUEST_ID					NUMBER	
    VENDOR_ID						NUMBER	
    EXEMPT_FLAG						VC(50)	
    REQUESTOR_ID					NUMBER	
    STATUS							VC(50)
    BU_ID							NUMBER	
    CH_REG_REQUEST_ID				NUMBER	
    PRIORITY						NUMBER	
    SUPPLIER_CATEGORY				VC(100)
    COUNTRY							VC(100)
    GREYSTAR_LOB					VC(100)
    COMPLIANCE_TYPE					VC(100)
    BU_NAME							VC(100)
    TEAM_MEMBER_TITLE				VC(100)
    PAY_GROUP						VC(100)
    PAYMENT_TERMS					VC(100)
    INVOICE_CURRENCY				VC(100)
    PAYMENT_CURRENCY				VC(100)
    REQUESTOR_NAME					VC(100)
    EXTERNAL_SYSTEM					VC(100)
    EXTERNAL_SYS_IDENTIFIER			VC(100)
    VENDOR_CODE						VC(100)
    DOC_TYPE						VC(100)
    ATTRIBUTE2						VC(100)
    ATTRIBUTE3						VC(100)
    ATTRIBUTE4						VC(100)
    ATTRIBUTE5						VC(100)
    ATTRIBUTE6						VC(100)
    ATTRIBUTE7						VC(100)
    ATTRIBUTE8						VC(100)
    ATTRIBUTE9						VC(100)
    ATTRIBUTE10						VC(100)
    INACTIVE_DATE					DATE	
    MESSAGE							VC(255)
    SOURCE							VC(100)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/