-- create tables

create table SOAPP_SUPPLIER_ADDRESS (
    id                   number generated by default on null as identity
                         constraint soapp_supplier_address_id_pk primary key,
    ADDRESS_ID           number,
    VENDOR_ID            number,
    PROFILE_ID           number,
    REG_REQUEST_ID       number,
    CH_REG_REQUEST_ID    number,
    VENDOR_SITE_ID       number,
    VENDOR_SITE_NAME     varchar2(100 char),
    ADDRESS_TYPE         varchar2(100 char),
    ADDRESS1             varchar2(100 char),
    ADDRESS2             varchar2(100 char),
    ADDRESS3             varchar2(100 char),
    ADDRESS4             varchar2(100 char),
    CITY                 varchar2(100 char),
    COUNTY               varchar2(100 char),
    STATE                varchar2(100 char),
    PROVINCE             varchar2(100 char),
    POSTAL_CODE          varchar2(100 char),
    STATUS               varchar2(50 char),
    ATTRIBUTE1           varchar2(100 char),
    ATTRIBUTE2           varchar2(100 char),
    ATTRIBUTE3           varchar2(100 char),
    ATTRIBUTE4           varchar2(100 char),
    ATTRIBUTE5           varchar2(100 char),
    ATTRIBUTE6           varchar2(100 char),
    ATTRIBUTE7           varchar2(100 char),
    ATTRIBUTE8           varchar2(100 char),
    ATTRIBUTE9           varchar2(100 char),
    ATTRIBUTE10          varchar2(100 char),
    COUNTRY              varchar2(150 char),
    CREATION_DATE        date not null,
    CREATED_BY           varchar2(255 char) not null,
    LAST_UPDATED_DATE    date not null,
    LAST_UPDATED_BY      varchar2(255 char) not null
);



-- triggers
create or replace trigger soapp_supplier_address_biu
    before insert or update
    on soapp_supplier_address
    for each row
begin
    if inserting then
        :new.CREATION_DATE := sysdate;
        :new.CREATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
    end if;
    :new.LAST_UPDATED_DATE := sysdate;
    :new.LAST_UPDATED_BY := coalesce(sys_context('APEX$SESSION','APP_USER'),user);
end soapp_supplier_address_biu;
/


-- APIs
create or replace package soapp_supplier_address_api
is

    procedure get_row (
        p_id        in  number,
        p_address_id   out  number,
        p_vendor_id   out  number,
        p_profile_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_vendor_site_id   out  number,
        p_vendor_site_name   out  varchar2,
        p_address_type   out  varchar2,
        p_address1   out  varchar2,
        p_address2   out  varchar2,
        p_address3   out  varchar2,
        p_address4   out  varchar2,
        p_city   out  varchar2,
        p_county   out  varchar2,
        p_state   out  varchar2,
        p_province   out  varchar2,
        p_postal_code   out  varchar2,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2,
        p_country   out  varchar2
    );

    procedure insert_row (
        p_id        in  number default null,
        p_address_id    in  number default null,
        p_vendor_id    in  number default null,
        p_profile_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_vendor_site_id    in  number default null,
        p_vendor_site_name    in  varchar2 default null,
        p_address_type    in  varchar2 default null,
        p_address1    in  varchar2 default null,
        p_address2    in  varchar2 default null,
        p_address3    in  varchar2 default null,
        p_address4    in  varchar2 default null,
        p_city    in  varchar2 default null,
        p_county    in  varchar2 default null,
        p_state    in  varchar2 default null,
        p_province    in  varchar2 default null,
        p_postal_code    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_country    in  varchar2 default null
    );

    procedure update_row (
        p_id        in  number default null,
        p_address_id    in  number default null,
        p_vendor_id    in  number default null,
        p_profile_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_vendor_site_id    in  number default null,
        p_vendor_site_name    in  varchar2 default null,
        p_address_type    in  varchar2 default null,
        p_address1    in  varchar2 default null,
        p_address2    in  varchar2 default null,
        p_address3    in  varchar2 default null,
        p_address4    in  varchar2 default null,
        p_city    in  varchar2 default null,
        p_county    in  varchar2 default null,
        p_state    in  varchar2 default null,
        p_province    in  varchar2 default null,
        p_postal_code    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_country    in  varchar2 default null
    );

    procedure delete_row (
        p_id              in number
    );
end soapp_supplier_address_api;
/

create or replace package body soapp_supplier_address_api
is

    procedure get_row (
        p_id        in  number,
        p_address_id   out  number,
        p_vendor_id   out  number,
        p_profile_id   out  number,
        p_reg_request_id   out  number,
        p_ch_reg_request_id   out  number,
        p_vendor_site_id   out  number,
        p_vendor_site_name   out  varchar2,
        p_address_type   out  varchar2,
        p_address1   out  varchar2,
        p_address2   out  varchar2,
        p_address3   out  varchar2,
        p_address4   out  varchar2,
        p_city   out  varchar2,
        p_county   out  varchar2,
        p_state   out  varchar2,
        p_province   out  varchar2,
        p_postal_code   out  varchar2,
        p_status   out  varchar2,
        p_attribute1   out  varchar2,
        p_attribute2   out  varchar2,
        p_attribute3   out  varchar2,
        p_attribute4   out  varchar2,
        p_attribute5   out  varchar2,
        p_attribute6   out  varchar2,
        p_attribute7   out  varchar2,
        p_attribute8   out  varchar2,
        p_attribute9   out  varchar2,
        p_attribute10   out  varchar2,
        p_country   out  varchar2
    )
    is 
    begin 
        for c1 in (select * from soapp_supplier_address where id = p_id) loop 
            p_address_id := c1.address_id;
            p_vendor_id := c1.vendor_id;
            p_profile_id := c1.profile_id;
            p_reg_request_id := c1.reg_request_id;
            p_ch_reg_request_id := c1.ch_reg_request_id;
            p_vendor_site_id := c1.vendor_site_id;
            p_vendor_site_name := c1.vendor_site_name;
            p_address_type := c1.address_type;
            p_address1 := c1.address1;
            p_address2 := c1.address2;
            p_address3 := c1.address3;
            p_address4 := c1.address4;
            p_city := c1.city;
            p_county := c1.county;
            p_state := c1.state;
            p_province := c1.province;
            p_postal_code := c1.postal_code;
            p_status := c1.status;
            p_attribute1 := c1.attribute1;
            p_attribute2 := c1.attribute2;
            p_attribute3 := c1.attribute3;
            p_attribute4 := c1.attribute4;
            p_attribute5 := c1.attribute5;
            p_attribute6 := c1.attribute6;
            p_attribute7 := c1.attribute7;
            p_attribute8 := c1.attribute8;
            p_attribute9 := c1.attribute9;
            p_attribute10 := c1.attribute10;
            p_country := c1.country;

        end loop;

    end get_row;
 
     procedure insert_row (
        p_id        in  number default null,
        p_address_id    in  number default null,
        p_vendor_id    in  number default null,
        p_profile_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_vendor_site_id    in  number default null,
        p_vendor_site_name    in  varchar2 default null,
        p_address_type    in  varchar2 default null,
        p_address1    in  varchar2 default null,
        p_address2    in  varchar2 default null,
        p_address3    in  varchar2 default null,
        p_address4    in  varchar2 default null,
        p_city    in  varchar2 default null,
        p_county    in  varchar2 default null,
        p_state    in  varchar2 default null,
        p_province    in  varchar2 default null,
        p_postal_code    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_country    in  varchar2 default null
    )
    is 
    begin 
        insert into soapp_supplier_address ( 
            id,
            address_id,
            vendor_id,
            profile_id,
            reg_request_id,
            ch_reg_request_id,
            vendor_site_id,
            vendor_site_name,
            address_type,
            address1,
            address2,
            address3,
            address4,
            city,
            county,
            state,
            province,
            postal_code,
            status,
            attribute1,
            attribute2,
            attribute3,
            attribute4,
            attribute5,
            attribute6,
            attribute7,
            attribute8,
            attribute9,
            attribute10,
            country
        ) values ( 
            p_id,
            p_address_id,
            p_vendor_id,
            p_profile_id,
            p_reg_request_id,
            p_ch_reg_request_id,
            p_vendor_site_id,
            p_vendor_site_name,
            p_address_type,
            p_address1,
            p_address2,
            p_address3,
            p_address4,
            p_city,
            p_county,
            p_state,
            p_province,
            p_postal_code,
            p_status,
            p_attribute1,
            p_attribute2,
            p_attribute3,
            p_attribute4,
            p_attribute5,
            p_attribute6,
            p_attribute7,
            p_attribute8,
            p_attribute9,
            p_attribute10,
            p_country
        );
    end insert_row;
 
     procedure update_row (
        p_id        in  number default null,
        p_address_id    in  number default null,
        p_vendor_id    in  number default null,
        p_profile_id    in  number default null,
        p_reg_request_id    in  number default null,
        p_ch_reg_request_id    in  number default null,
        p_vendor_site_id    in  number default null,
        p_vendor_site_name    in  varchar2 default null,
        p_address_type    in  varchar2 default null,
        p_address1    in  varchar2 default null,
        p_address2    in  varchar2 default null,
        p_address3    in  varchar2 default null,
        p_address4    in  varchar2 default null,
        p_city    in  varchar2 default null,
        p_county    in  varchar2 default null,
        p_state    in  varchar2 default null,
        p_province    in  varchar2 default null,
        p_postal_code    in  varchar2 default null,
        p_status    in  varchar2 default null,
        p_attribute1    in  varchar2 default null,
        p_attribute2    in  varchar2 default null,
        p_attribute3    in  varchar2 default null,
        p_attribute4    in  varchar2 default null,
        p_attribute5    in  varchar2 default null,
        p_attribute6    in  varchar2 default null,
        p_attribute7    in  varchar2 default null,
        p_attribute8    in  varchar2 default null,
        p_attribute9    in  varchar2 default null,
        p_attribute10    in  varchar2 default null,
        p_country    in  varchar2 default null
    )
    is 
    begin 
        update  soapp_supplier_address set 
            id = p_id,
            address_id = p_address_id
,
            vendor_id = p_vendor_id
,
            profile_id = p_profile_id
,
            reg_request_id = p_reg_request_id
,
            ch_reg_request_id = p_ch_reg_request_id
,
            vendor_site_id = p_vendor_site_id
,
            vendor_site_name = p_vendor_site_name
,
            address_type = p_address_type
,
            address1 = p_address1
,
            address2 = p_address2
,
            address3 = p_address3
,
            address4 = p_address4
,
            city = p_city
,
            county = p_county
,
            state = p_state
,
            province = p_province
,
            postal_code = p_postal_code
,
            status = p_status
,
            attribute1 = p_attribute1
,
            attribute2 = p_attribute2
,
            attribute3 = p_attribute3
,
            attribute4 = p_attribute4
,
            attribute5 = p_attribute5
,
            attribute6 = p_attribute6
,
            attribute7 = p_attribute7
,
            attribute8 = p_attribute8
,
            attribute9 = p_attribute9
,
            attribute10 = p_attribute10
,
            country = p_country
        where id = p_id;
    end update_row;
 
     procedure delete_row (
        p_id              in number
    )
    is
    begin
        delete from soapp_supplier_address where id = p_id;
    end delete_row;
end soapp_supplier_address_api;
/

-- Grant select, insert, update, delete access to GSAPEX schema for soapp_supplier_address table
GRANT SELECT, INSERT, UPDATE, DELETE ON GSSOAPP.soapp_supplier_address TO gsapex;
/
-- Grant execute privilege on soapp_supplier_address_api api to GSAPEX schema
GRANT EXECUTE ON GSSOAPP.soapp_supplier_address_api TO gsapex;
/
-- Create synonyms for easier access in GSAPEX schema
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_address FOR GSSOAPP.soapp_supplier_address;
/
CREATE OR REPLACE SYNONYM gsapex.soapp_supplier_address_api FOR GSSOAPP.soapp_supplier_address_api;
-- Generated by Quick SQL 1.2.9 5/28/2024, 5:27:38 PM

/*
SOAPP_SUPPLIER_ADDRESS
    ADDRESS_ID	            NUMBER,	
    VENDOR_ID	            NUMBER,	
    PROFILE_ID	            NUMBER,	
    REG_REQUEST_ID	        NUMBER,	
    CH_REG_REQUEST_ID	    NUMBER,	
    VENDOR_SITE_ID	        NUMBER,	
    VENDOR_SITE_NAME	    Vc(100),
    ADDRESS_TYPE	        Vc(100),
    ADDRESS1	            Vc(100),
    ADDRESS2	            Vc(100),
    ADDRESS3	            Vc(100),
    ADDRESS4	            Vc(100),
    CITY	                Vc(100),
    COUNTY	                Vc(100),
    STATE	                Vc(100),
    PROVINCE	            Vc(100),
    POSTAL_CODE	            Vc(100),
    STATUS	                Vc(50),
    ATTRIBUTE1	            Vc(100),
    ATTRIBUTE2	            Vc(100),
    ATTRIBUTE3	            Vc(100),
    ATTRIBUTE4	            Vc(100),
    ATTRIBUTE5	            Vc(100),
    ATTRIBUTE6	            Vc(100),
    ATTRIBUTE7	            Vc(100),
    ATTRIBUTE8	            Vc(100),
    ATTRIBUTE9	            Vc(100),
    ATTRIBUTE10	            Vc(100),
    COUNTRY	                Vc(150)

 Non-default options:
# settings = {"apex":"Y","auditcols":"Y","createdcol":"CREATION_DATE","updatedcol":"LAST_UPDATED_DATE","updatedbycol":"LAST_UPDATED_BY","db":"19c","pk":"IDENTITY","api":"Y"}

*/